### ISSUE TITLE
Mislabeled codes

### ISSUE THREAD

**Issue by Beliavsky** [urbanjost/M_datapac#1]
In the Readme, the codes below are mislabeled "lognormal" instead of "Cauchy".

[CAUCDF](https://github.com/urbanjost/M_datapac/blob/main/src/source/caucdf.ffinc) - compute the lognormal cumulative distribution function
[CAUPDF](https://github.com/urbanjost/M_datapac/blob/main/src/source/caupdf.ffinc) - compute the lognormal probability density function
[CAUPPF](https://github.com/urbanjost/M_datapac/blob/main/src/source/cauppf.ffinc) - compute the lognormal percent point function
[CAURAN](https://github.com/urbanjost/M_datapac/blob/main/src/source/cauran.ffinc) - generate lognormal random numbers

**Comment by urbanjost** [comment]
The index was based on the NIST DATAPAC site;  so I sent them a note about the Cauchy procedures being listed twice and the second listing being obvisiously  where the missing lognormal procedures should be described, as the list is otherwise alphabetical. Corrected on this site.  Note that index will be removed if I can the man-pages and ford(1)/doxygen(1) documentation finished. Thanks; any tests, etc. are appreciated.
